name: CI/CD with Docker

on:
  push:
    branches:
      - main  # Atau ganti dengan nama branch Anda

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Make envfile
      uses: SpicyPizza/create-envfile@v1.2
      with:
        envkey_PORT: 4000

    - name: Build Docker image
      run: docker build -t ${{ secrets.DOCKERHUB_USERNAME }}/test-ci:latest .

    - name: Push Docker image to registry (optional)
      uses: docker/build-push-action@v2
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}
        repository: ${{ secrets.DOCKERHUB_USERNAME }}/test-ci:latest
        tag_with_ref: true

    - name: Deploy to Docker (optional)
      run: |
        docker-compose -f ./docker-compose.yml up -d
