name: Node.js Docker Workflow

on:
  push:
    branches:
      - main  # Sesuaikan dengan nama branch Anda

jobs:
  build:
    name: Build and Run
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Make envfile
      uses: SpicyPizza/create-envfile@v1.3
      with:
        envkey_PORT: 8080

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1

    - name: Login to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}

    - name: Build Docker image
      run: docker build . -t ${{ secrets.DOCKERHUB_USERNAME }}/test-ci

    - name: Run Docker container
      run: docker run -d -p 8080:3000 ${{ secrets.DOCKERHUB_USERNAME }}/test-ci
